app_inicio:
    path: /
    controller: App\Controller\InicioController::index
    methods: [GET]

app_activities:
    path: /activities
    controller: App\Controller\ActivitiesController::index
    methods: [GET]

app_contact:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: [GET, POST]

app_profile:
    path: /profile
    controller: App\Controller\profileController::index
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: [GET, POST]
