app_inicio:
    path: /
    controller: App\Controller\InicioController::index
    methods: [GET]

app_activities:
    path: /activities
    controller: App\Controller\ActivityController::activities
    methods: [GET]

app_contact:
    path: /contact
    controller: App\Controller\ContactController::contactForm
    methods: [GET, POST]


app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: [GET, POST]

app_show_image:
    path: /images/{imageName}
    controller: App\Controller\ImageController::show
    methods: [GET]
